name: Tests
on: push

jobs:
  test:
    name: Run tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: sudo python -m unittest discover -f -s tests